name: tv_app_broadcast
description: 农贸市场的广播程序
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 1.0.4
  flutter_downloader: 1.7.3
  path_provider: 2.0.9
  permission_handler: 10.0.2
  url_launcher: 6.1.6

  flutter_inappwebview: 5.7.2+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  integration_test:
    sdk: flutter

  pedantic: ^1.8.0

flutter:

  uses-material-design: true